actors:
  miyamoto:
    image_url: /images/actors/miyamoto.jpg
    name: yahsan2
    url: https://twitter.com/yahsan2
  sugi:
    image_url: /images/actors/sugi.jpg
    name: koheiSG
    url: https://twitter.com/koheiSG
  terada:
    image_url: /images/actors/terada.jpg
    name: naokazu_terada
    url: https://twitter.com/naokazu_terada
author: alice
description: オンラインコミュニティ”DevelopersJP”周辺にたむろするノラ猫エンジニアたちが、近頃流行りのテック系ポッドキャストを“サカナ“ 🐟 に話す番組です。
description_long: オンラインコミュニティ”DevelopersJP”周辺にたむろするノラ猫エンジニアたちが、近頃流行りのテック系ポッドキャストを“サカナ“ 🐟 に話す番組です。DevelopersJPは、フリーランスや小さな会社のエンジニアが集って、わいわいワイワイしてるSlack のことです。
email: noracast.podcast@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics:
hashtag: noracast
itunes_podcast_url:
keywords: comma,separated,keywords
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: noracast
url: https://noracast.netlify.com
